= elClubo, ¿Ahora así suenan?

:hp-tags: música, review

Con mi papá tengo la costumbre de compartir música, y he de admitir que gracias a él tengo ese gusto y cariño hacia la misma. Cuando le preguntan: "¿Qué música escuchas?" su respuesta siempre será "De todo un poco" y es porque literalmente escucha de todo, desde Cumbia, pasando por Tech-House, Heavy Metal, Hip Hop, hasta llegar al Reguetón.

Resulta ser que hoy me compartió una canción de elClubo, una banda guatemalteca que todos conocemos y que personalmente no me gusta, su sonido siempre me pareció llano y aburrido. Aun así, suelo escuchar canciones de artistas y grupos que no me gustan para conocerlos más y así tener fundamentos del por qué no me gustan, y así fue como me di una sorpresa.



video::j9BNp0iZO_g[youtube,width=800,height=450]

Capturaron toda mi atención desde los primeros segundos y para el final, me di cuenta que posee todas las cualidades de una canción memorable a mi gusto: una batería firme y notoria, una entrega vocal agresiva que incluso involucra un grito semi-gutural, guitarras en una afinación baja que da más cuerpo y profundidad, un solo que quizá no se caracterice por ser "técnico" pero que se acopla perfectamente y se disfruta, ¡¡UN BAJO QUE SE ESCUCHA!! y por supuesto, una lírica que a la primera puede ser interpretada y analizada.

Lanzada el 6 de junio de 2019, elClubo emerge de nuevo, con un tono más agresivo, una producción de muy buena calidad y un video que se convierte en una experiencia audiovisual placentera. Así, me toma por sorpresa a mí y a los oídos de todos, logrando una reacción de su público, haciendo notoria su ambición por querer dar un paso más allá en su evolución como banda, y sobre todo ganarse mi respeto. Espero con ansias más música de ellos, que sigan el camino que con esta canción comenzaron a pavimentar.
